name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  apt: libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libxcursor-dev libxfixes-dev libxi-dev libxrandr-dev libxinerama-dev

jobs:
  build_test:
    name: "Main build and test using -> '${{ matrix.THIS_OPTIM }}'"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        THIS_OPTIM: [ "", "--release=fast", "--release=safe", "--release=small" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install zig
        uses: mlugg/setup-zig@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.apt }}

      - name: Zig details
        run: |
          zig version
          zig env

      - name: Build now
        run: |
          zig build ${{ matrix.THIS_OPTIM }}  --summary all

      - name: Test it
        run: zig build test ${{ matrix.THIS_OPTIM }} --summary all

      - name: check bin size
        run: ls -lht zig-out/bin

  fmt:
    name: Check the formatting
    runs-on: ubuntu-24.04
    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Install zig
        uses: mlugg/setup-zig@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.apt }}

      - name: Run fmt check
        run: zig fmt --check . --exclude zig-cache

  code_coverage:
    name: Check the code coverage
    runs-on: ubuntu-22.04
    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.apt }} kcov

      - name: Check coverage
        run: zig build test -Dtest_coverage  --summary all

      - name: Download artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_json_files
          path: |
            kcov-out/*/coverage.json
